"""add description to products2

Revision ID: a017a430c5fb
Revises: 7a9ff16ca548
Create Date: 2026-04-20 13:23:03.222772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a017a430c5fb'
down_revision: Union[str, Sequence[str], None] = '7a9ff16ca548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.execute("UPDATE products SET description = 'Описание не указано' WHERE description IS NULL")
    op.alter_column('products', 'description', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
